name: Dependency Submission
on:
  push:
    branches:
      - master
    paths:
      - "**.gradle.kts"
      - ".github/workflows/dependency-submission.yml"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Run snapshot multimodule
        uses: mikepenz/gradle-dependency-submission@91b021ee7e1ec04cb057c055cc80c5124e70242c
        with:
          gradle-build-module: |-
            :core
            :spesification
