name: Publish release
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v5
        with:
          ref: master
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto
          cache: gradle
      - name: Build JAR
        run: ./gradlew clean build -x test # Creates a combined JAR of project and runTime dependencies.
      - name: Publish artifact
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${NEW_VERSION}
          ./gradlew -Pversion="${NEW_VERSION}" publish
